### ISSUE TITLE
Assisted Installer on OCP Cluster - discussion and support

### ISSUE THREAD

**Issue by pmallan** [redhat-ztp/ztp-cluster-deploy#129]
Assisted Installer could be installed on provision server but this does not provide high availability. As we need AI for any future worker node additions, probably better option is to deploy it on OCP. We tried to do it and below are our observations

Installed Assisted Service on OCP Cluster (Management cluster) by using this repo https://github.com/openshift/assisted-service. As you see, these 2 routes have been exposed by  AI:
https://assisted-installer.apps.devmgmtcluster.rtp.raleigh.ibm.com/ - assisted service accessible over https without authentication
http://assisted-installer-ui.apps.devmgmtcluster.rtp.raleigh.ibm.com/ - AI UI accessible over http without authentication 

![image](https://user-images.githubusercontent.com/79190301/122046128-261fc100-cdfc-11eb-8542-96245c280522.png)

- The plan is to deploy AI in management cluster along with CP4NA, RHACM and Argocd.
- AI UI is http based. is there a plan to make it https and option to integrate with ldap server for authentication purpose?
- AI service is https however unauthenticated. Is there a plan to make it authenticated?

**Comment by yrobla** [comment]
This is under discussion as new AI is not having UI support, and it's also very integrated with ACM.  Also they are dropping support for AI on-prem. You'd need to talk with AI team in order to check for latest AI status and future plans.
