### ISSUE TITLE
[ibm-telco]Stable/4.7 for restricted-network -  code is broken with latest Assisted Installer

### ISSUE THREAD

**Issue by jvijayku** [redhat-ztp/ztp-cluster-deploy#151]
The code which brought in support for restricted-network install would not work with latest Assisted Install. Please see following for more details - https://github.com/sonofspike/cluster_mgnt_roles/issues/52

**Comment by maheshd2** [comment]
We are able to proceed with the installation by commenting below lines of code in the file ` common-roles/create-cluster/tasks/main.yml`
```
- name: Get discovery ignition file
  uri:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTERS }}/{{ cluster_id }}/discovery-ignition"
    method: GET
    status_code: [200]
    return_content: True
  register: discovery_ignition

- debug:
    var: discovery_ignition.json
  when: debug | bool == True

- name: "Copy discovery_ignition.json"
  copy:
    content: "{{ discovery_ignition.json }}"
    dest: discovery-ignition.txt
  delegate_to: localhost
  become: no
```

**Comment by yrobla** [comment]
We will not be supporting adding these features into master branch, as the paths have diverged. Please feel free to fork this repo, to add your changes as needed.
