### ISSUE TITLE
[ibm-telco] Documentation gaps w.r.t depedent packages

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#32]
Hi yolanda,

As discussed here are the details of the documentation gaps which I observed while running ztp playbooks:

Master Host Operating System: RHEL 8.2

Below are the few dependent packages which were missing from documentation.

1. Ansible

```
sudo subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms
sudo yum install ansible -y
```

2. Other ansible modules(documented)
```
ansible-galaxy collection install community.libvirt
ansible-galaxy collection install containers.podman
ansible-galaxy collection install community.general
```

3. Install git and make commands
```
yum install git
yum install make -y
```

After "prepare-environment" step

4. Create the dir path even though we are not using /opt/network-scrips
```
mkdir -p /opt/network-config/
```

5. Create the below soft links for python packages/
```
mkdir -p /usr/local/lib/python3.6/site-packages/
ln -s /usr/lib/python3.6/site-packages/ /usr/local/lib/python3.6/site-packages/
```

6. Create the soft links for aicli command
```
# which aicli
/usr/local/bin/aicli
ln -s /usr/local/bin/aicli /usr/bin/aicli
```

7. Install following python modules
```
python3 -m pip install prettytable
yum install libvirt-python3
```

8. Add ansible_user under inventory/hosts
```
ansible_user=root
```

Few Other things which we can add to the documentation are:

1. Create a bridge and move the IP to the bridge.

```
[root@ztphost ztp]# cat /etc/sysconfig/network-scripts/ifcfg-ens3f1
TYPE=Ethernet
BOOTPROTO=none
DEFROUTE=yes
NAME=ens3f1
UUID=d6cffa5e-fba3-47a6-a8e8-0cc7e458f46e
DEVICE=ens3f1
ONBOOT=yes
BRIDGE=ztp-br
[root@ztphost ztp]#
[root@ztphost ztp]# cat /etc/sysconfig/network-scripts/ifcfg-ztp-br
TYPE=Bridge
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
NAME=ztp-br
DEVICE=ztp-br
ONBOOT=yes
IPADDR=9.42.98.150
NETMASK=255.255.255.0
GATEWAY=9.42.98.1
```

2. Set the hostname, DNS entries, and /etc/hosts
```
sudo hostnamectl set-hostname ztphost.rtp.raleigh.ibm.com
sudo hostnamectl set-hostname --transient ztphost.rtp.raleigh.ibm.com


[rhacm@ztphost home]$ cat /etc/resolv.conf
# Generated by NetworkManager
search rtp.raleigh.ibm.com
nameserver 8.8.8.8


[root@ztphost network-scripts]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

9.42.98.151     api.ztp.rtp.raleigh.ibm.com
9.42.98.152     *.apps.ztp.rtp.raleigh.ibm.com

9.42.98.150  ztphost.rtp.raleigh.ibm.com
```

3. RHEL Subscription
```
subscription-manager register --auto-attach --force
```

4. Generate the SSH key pair
```
ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
```

4. More details of /opt/network-config with an example

**Comment by yrobla** [comment]
Thanks for the feedback, we'll fix that

**Comment by yrobla** [comment]
For subscription, we will not take care of it. This playbook can be run on centos or RHEL... so up to the user to configure the system and subscriptions properly. We will just take care of installing the dependencies

**Comment by yrobla** [comment]
Issues with prettytable and other dependencies in assisted-installer-cli should be fixed

**Comment by yrobla** [comment]
For the dependencies , there is already a file, requirements.yml . You can install the dependencies with ansible-galaxy collection pointing to that file

**Comment by yrobla** [comment]
For the aicli path, we will not create the softlink. Instead, we've added the right path into the env vars in ansible, so it should be executed properly

**Comment by yrobla** [comment]
ansible_user not referenced anymore in the playbooks
