### ISSUE TITLE
[ibm-telco] Playbook "acm-hub" is not able to deploy ACM successfully.

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#41]
Hi yolanda,

After deploying the cluster using playbooks "ai-deploy-cluster-remoteworker",  I ran the "acm-hub" playbooks. The playbooks executed successfully, the ACM operator is shown deployed successfully. But later I saw some of the pods are failing because of cpu resource issue. Since the master VMs are auto deployed, please let us know how we can have a control on these resources.

![image](https://user-images.githubusercontent.com/27758674/106695270-421a8700-6600-11eb-8d64-bf8ff41c0bf1.png)

![image](https://user-images.githubusercontent.com/27758674/106695608-f1575e00-6600-11eb-9a79-c7bcaa933280.png)

![image](https://user-images.githubusercontent.com/27758674/106695658-0cc26900-6601-11eb-9138-d562b201e483.png)

**Comment by yrobla** [comment]
As discussed in the chat, we will close this issue. Our playbooks are not really targetting the ACM hub cluster deployment, but the spoke clusters and remote workers. You can deploy openshift in any other way, and then you can size the masters with the right memory/cpu, or even use baremetal nodes for it. Once you have deployed, you can apply the ACM manifests on it, but the deployment of the openshift cluster for ACM is not on the scope of this tool.
