### ISSUE TITLE
[ibm-telco] We should be able to run the playbooks from a remote host

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#42]
Currently the provisioning host is 'localhost'. I mean the playbooks will be executed on the same master host machine. But we have run the playbooks by changing the provisioning host to a remote host and verify it works.

Since the playbooks will be run via ansible driver in case of TNCM (ALM), we have to verify and ensure this feature.

**Comment by yrobla** [comment]
That is already done. See https://github.com/redhat-ztp/ztp-cluster-deploy/blob/master/ai-deploy-cluster-remoteworker/inventory/hosts.sample#L38 . You can add a host ip there, instead of localhost, and the playbook will work
