### ISSUE TITLE
[ibm-telco] Worker node addition failing due to issue with root file system

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#54]
![image](https://user-images.githubusercontent.com/27758674/107182892-a58f2500-6a03-11eb-9cec-0b1d7c9ccaab.png)

**Comment by yrobla** [comment]
This normally happens due to a mismatch on the cluster version and the rootfs.. for 4.7 you need to point to https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest-4.7/rhcos-4.7.0-fc.4-x86_64-live-rootfs.x86_64.img
