### ISSUE TITLE
[ibm-telco] Worker node installation fails if node is still in "insufficient" state.

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#63]
It is observed that "add-remote-workers" role will be completed when the node reaches "insufficient" state.
And soon the node will enter into "known" state from "insufficient" state.

So, the next role "deploy-cluster-day2" will install worker successfully only if the node is in "known" state.

Other case, if the node is still in "insufficient" state, the role "deploy-cluster-day2" will complete without installing the cluster.

In our lab environment, I observed this when the worker node was taking some time to reach "known" state from "insufficient" state.

**Comment by yrobla** [comment]
It is fine, the nodes comes with insufficient state and they end like that in the add-remote-workers. Then in the deploy-cluster-day2 we just update the network settings for the nodes and start the installation. They shold be entering into known state, then installed.

**Comment by maheshd2** [comment]
It is observed that even in the master branch, the `deploy-cluster-day2` role will not wait for the worker nodes to reach `known` state. `aicli start cluster <cluster_name>` is being issue without checking host state.
