### ISSUE TITLE
The error was: 'hw' is undefined\n\nThe error appears to be in '/root/ztp-cluster-deploy/acm-spoke/enroll-clusters.yaml'

### ISSUE THREAD

**Issue by pmallan** [redhat-ztp/ztp-cluster-deploy#89]
@yrobla Please update this enroll-clusters.yaml as it throws above error when trying to import cluster

I have changed this line and it worked
- name: Import cluster to ACM
  shell: "{{ temporary_path }}/import_cluster.sh {{ hostvars[item].name }} {{ hostvars[item].profile }} {{ kubeconfig_hub_path }} {{ temporary_path }} {{ hw }}"

to 

- name: Import cluster to ACM
  shell: "{{ temporary_path }}/import_cluster.sh {{ hostvars[item].name }} {{ hostvars[item].profile }} {{ kubeconfig_hub_path }} {{ temporary_path }} {{  hostvars[item].hw }}"

**Comment by yrobla** [comment]
@serngawy can you take a look at that? may be just a missing inventory setting?

**Comment by yrobla** [comment]
I backported the change to 4.7 branch. Should be fixed now.
